Gustavo A. Aparicio V. - 20232006091

In [5]:
import pandas as pd # Importa la biblioteca 'pandas' y se le asigna un nombre 'pd' para facilidad
pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv") # Instrucción para leer un archivo CSV, usando el método 'read_csv'

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [4]:
from google.colab import drive # Importa la biblioteca 'drive' de 'google.colab', utilizada para el funcionamiento de los códigos
drive.mount('/content/drive') # Intrucción para tener acceso a los archivos del 'google drive'

Mounted at /content/drive

In [9]:
cities = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["City"]) # Dataframe con la instrucción para leer un archivo CSV, pero solo la columna 'city' por el agurmento 'usecols'
pop = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["Population"]) # Dataframe con la instrucción para leer un archivo CSV, pero solo la columna 'population' por el agurmento 'usecols'
pop.head() # Método 'head()' para mostrar en consola/pantalla las cinco (5) primeras filas
cities.tail() # Método 'tail()' para mostrar en consola/pantalla las cinco (5) últimas filas

        City
596  Lobitos
597   Bremen
598   Harare
599    Lagos
600   Oshawa

In [12]:
cities.head() # Método 'head()' para mostrar en consola/pantalla las cinco (5) primeras filas

            City
0         Kajuru
1           Leon
2            Osh
3  Shumikhinskiy
4       Bundoran

In [13]:
cities.tail() # Método 'tail()' para mostrar en consola/pantalla las cinco (5) últimas filas

        City
596  Lobitos
597   Bremen
598   Harare
599    Lagos
600   Oshawa

In [14]:
pop.tail(n = 8) # Método 'tail()' para mostrar en consola/pantalla un número determinado de filas 'n=8' empezando desde la última

     Population
593       16755
594       16325
595       16905
596       10024
597        5768
598       16679
599       24800
600       13000

In [15]:
cities.count() # Método 'count()' para contar las filas del archivo CSV del dataframe 'cities'

City    601
dtype: int64

In [16]:
pop.count() # Método 'count()' para contar las filas del archivo CSV del dataframe 'pop'

Population    601
dtype: int64

In [17]:
cities.describe() # Método 'describe()' muestra un resumen estadístico del dataframe 'cities'

               City
count           601
unique          578
top     San Antonio
freq              4

In [18]:
pop.describe() # Método 'describe()' muestra un resumen estadístico del dataframe 'pop'

         Population
count    601.000000
mean   13932.415973
std     6765.873291
min     2528.000000
25%     7801.000000
50%    13966.000000
75%    19752.000000
max    38745.000000

In [20]:
# cities.sort_values()
cities.sort_values(by = ["City"], ascending = False) # Método 'sort_values()' organiza los datos del dataframe 'cities' de acuerdo a la columna 'city', alfabéticamente desde la Z hasta al A por el argumento 'ascending = False'

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang
..             ...
467       Alcoutim
212       Alarobia
472          Aketi
66          Aizhai
581          Abuja

[601 rows x 1 columns]

In [ ]:
cities.sort_values(by = ["City"], ascending = True).head() # Método 'sort_values()' organiza los datos del dataframe 'cities' de acuerdo a la columna 'city, alfabéticamente desde la A hasta la Z por el argumento 'ascending = True', y solo muestra las cinco (5) primeras filas por el método 'head()'

         City
581     Abuja
66     Aizhai
472     Aketi
212  Alarobia
467  Alcoutim

In [21]:
cities = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["City"])
cities
cities.sort_values(by = ["City"], ascending = False, inplace = True) # Argumento 'inplace = True' ordena que los cambios en el orden se harán en el mismo dataframe, no en una copia
cities

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang
..             ...
467       Alcoutim
212       Alarobia
472          Aketi
66          Aizhai
581          Abuja

[601 rows x 1 columns]

In [24]:
cities.sort_index() # Método 'sort_index()' ordena el dataframe 'cities' por el número de fila

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
..             ...
596        Lobitos
597         Bremen
598         Harare
599          Lagos
600         Oshawa

[601 rows x 1 columns]

In [26]:
#cities
pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv")
cities.sort_index(ascending = True, inplace = True) # Método 'sort_index()' ordena el dataframe 'cities' por el número de fila, desde 0 a 600 gracias al argumento 'ascending = True' y aplica los cambios en el mismo dataframe gracias al argumento 'inplace = True'
cities

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
..             ...
596        Lobitos
597         Bremen
598         Harare
599          Lagos
600         Oshawa

[601 rows x 1 columns]

In [ ]:
print(cities) # Imprime el dataframe 'cities'

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
..             ...
596        Lobitos
597         Bremen
598         Harare
599          Lagos
600         Oshawa

[601 rows x 1 columns]

In [ ]:
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv") # Crea un dataframe llamado 'data' incluyendo todas sus columnas
data

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [27]:
data = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", index_col = ["City"]) # Argumento 'index_col' determina la columna 'city' como el índice del dataframe 'data'
data = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["City"])
data = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv")
data.head()

            City     Country  Population
0         Kajuru    Botswana       21722
1           Leon       Spain        5629
2            Osh  kyrgyzstan        5679
3  Shumikhinskiy      Russia       10085
4       Bundoran     Ireland       23421

In [55]:
#data[1] # Instrucción mal digitada, no retorna nada
 # --- ADICIONAL --- #
data.iloc[1] # Instrucción para acceder a una fila en concreto

City           Leon
Country       Spain
Population     5629
Name: 1, dtype: object

In [ ]:
cities = data["City"] # Dataframe 'cities' cuya info es parte de otro dataframe 'data' donde solo se accede a la columna 'cities'
cities.head()

0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
Name: City, dtype: object

In [57]:
#cities[19] # Instrucción mal digitada, no retorna nada
cities.iloc[19] # Instrucción correcta

City    Fort Worth
Name: 19, dtype: object

In [58]:
cities[10:20] # Instrucción para acceder a cierto intervalo de filas

           City
10          Ise
11       Volovo
12       Caujul
13   Kutloanong
14     Kobuleti
15       Senlis
16       Wufeng
17       Picton
18  Johor Bahru
19   Fort Worth

In [ ]:
cities[:15] # Instrucción para acceder desde la fila 0 hasta la fila 'n'

0            Kajuru
1              Leon
2               Osh
3     Shumikhinskiy
4          Bundoran
5         La Paloma
6             Tutup
7           Ondores
8           Heredia
9              Gaio
10              Ise
11           Volovo
12           Caujul
13       Kutloanong
14         Kobuleti
Name: City, dtype: object

In [ ]:
cities[0:26:2] # Instrucción para acceder desde la fila 0 hasta la fila 'n' de dos (2) en dos (2)

0          Kajuru
2             Osh
4        Bundoran
6           Tutup
8         Heredia
10            Ise
12         Caujul
14       Kobuleti
16         Wufeng
18    Johor Bahru
20     Santa Cruz
22         Maubin
24          Itzer
Name: City, dtype: object

In [ ]:
cities[-10:] # Instrucción para acceder desde la última fila hasta la fila '-n'

591    Bagumbayan
592      Tuanshan
593       Sapporo
594    Cocachacra
595        Kurjan
596       Lobitos
597        Bremen
598        Harare
599         Lagos
600        Oshawa
Name: City, dtype: object

In [66]:
cities.iloc[[3, 5, 7]] # Método e Instrucción para acceder a ciertas filas en específico
#cities.sort_values()

            City
3  Shumikhinskiy
5      La Paloma
7        Ondores

In [67]:
#Retrieving data from a series by index label:

#city = pd.read_csv("Cities.csv", usecols = ["City", "Country"])
city = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["City", "Country"], index_col = "City") # Argumentos para acceder solo a las columnas 'city' y 'country', convirtiendo 'city' es el index
city = city["Country"]
city

City
Kajuru             Botswana
Leon                  Spain
Osh              kyrgyzstan
Shumikhinskiy        Russia
Bundoran            Ireland
                    ...
Lobitos                Peru
Bremen              Germany
Harare             Zimbabwe
Lagos               Nigeria
Oshawa               Canada
Name: Country, Length: 601, dtype: object

In [69]:
city[0] # Instrucción que retorna la info de la fila 'n' de la columna 'city'

<ipython-input-69-8f5a1a4338dc>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city[0]

'Botswana'

In [72]:
city["Lobitos"] # Instrucción que retorna la info de 'lobitos' (en este caso, encontró dos resultados)

City
Lobitos    Peru
Lobitos    Peru
Name: Country, dtype: object

In [75]:
city["Kajuru"] # Instrucción para retorna la info de 'kajuru' (encontró un solo resultado)

'Botswana'

In [ ]:
city.sort_index(inplace = True, ascending = True) # Instrucción y argumentos ya explicados
city

City
Abuja                                     Nigeria
Aizhai                                      China
Aketi            Democratic Republic of the Congo
Alarobia                               Madagascar
Alcoutim                                 Portugal
                               ...
Zhongshangang                               China
Zhongshangang                               China
Zhongxing                                   China
Zhuoshui                                    China
Zliv                               Czech Republic
Name: Country, Length: 601, dtype: object

In [ ]:
city["Abuja":"Bremen"] # Instrucción para acceder desde cierto valor de 'city' hasta cierto valor del mismo

City
Abuja                  Nigeria
Bantawora            Indonesia
Waihai                   China
Zhangcun                 China
Plaeng Yao            Thailand
Guja                     Japan
Caijiagang               China
Consuelo           Philippines
Santa Magdalena    Philippines
Gemblengmulyo        Indonesia
Bagumbayan         Philippines
Tuanshan                 China
Sapporo                  Japan
Cocachacra                Peru
Kurjan                 Albania
Lobitos                   Peru
Bremen                 Germany
Name: Country, dtype: object

In [ ]:
city[:"Bremen"] # Instrucción para acceder desde el primer valor de 'city' hasta el valor específicado 'bremen'

City
Kajuru             Botswana
Leon                  Spain
Osh              kyrgyzstan
Shumikhinskiy        Russia
Bundoran            Ireland
                    ...
Sapporo               Japan
Cocachacra             Peru
Kurjan              Albania
Lobitos                Peru
Bremen              Germany
Name: Country, Length: 598, dtype: object

In [ ]:
city[["Bolgar", "Abuja", "Osh"]] # Instrucción para acceder solo a tres filas de 'city'

City
Bolgar        Russia
Abuja        Nigeria
Osh       kyrgyzstan
Name: Country, dtype: object

In [ ]:
city.head(10) # Método 'head()' para acceder a las n primeras filas (en este caso, 10)

City
Abuja                                      Nigeria
Aizhai                                       China
Aketi             Democratic Republic of the Congo
Alarobia                                Madagascar
Alcoutim                                  Portugal
Alis                                          Peru
Alvaro Obregon                              Mexico
Amargosa                                    Brazil
Amuru                                       Uganda
Anan                                         Japan
Name: Country, dtype: object

In [ ]:
city["Abuja": "Anan": 2] # Instrucción para acceder desde 'abuja hasta 'anan' de dos (2) en dos (2)

City
Abuja                                      Nigeria
Aketi             Democratic Republic of the Congo
Alcoutim                                  Portugal
Alvaro Obregon                              Mexico
Amuru                                       Uganda
Name: Country, dtype: object

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/dataAnalisys/Cities.csv", usecols = ["City", "Country"], index_col = "City") # Instrucciones y argumentos ya explicados
data.sort_index(inplace = True)
data

                                        Country
City
Abuja                                   Nigeria
Aizhai                                    China
Aketi          Democratic Republic of the Congo
Alarobia                             Madagascar
Alcoutim                               Portugal
...                                         ...
Zhongshangang                             China
Zhongshangang                             China
Zhongxing                                 China
Zhuoshui                                  China
Zliv                             Czech Republic

[601 rows x 1 columns]

In [ ]:
city = data["Country"] # Instrucciones y argumentos ya explicados
city

City
Abuja                                     Nigeria
Aizhai                                      China
Aketi            Democratic Republic of the Congo
Alarobia                               Madagascar
Alcoutim                                 Portugal
                               ...
Zhongshangang                               China
Zhongshangang                               China
Zhongxing                                   China
Zhuoshui                                    China
Zliv                               Czech Republic
Name: Country, Length: 601, dtype: object

In [78]:
city.get(0) # Método 'get()' obtiene el valor correspondiente a la fila 'n' (en este caso, fila 0)

<ipython-input-78-3b8953b357aa>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city.get(0)

'Botswana'

In [81]:
city.get([1, 5]) # Método 'get()' obtiene valores correspondientes de las filas desde 'n' hasta 'n' (en este caso, desde 1 hasta 5)

<ipython-input-81-26f1bf906b27>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city.get([1, 5]) # Método 'get()' obtiene valores correspondientes de las filas desde 'n' hasta 'n' (en este caso, desde 1 hasta 5)

City
Leon           Spain
La Paloma    Uruguay
Name: Country, dtype: object

In [86]:
#city.get(["Aizahai", "Alis"])
print(city.get(["Aizahai", "Alis"])) # Imprime los valores de las filas 'aizahai' y 'alis', como no existen, devuelve 'none'
print(city.get(["Leon", "La Paloma"])) # Imprime los valores de las filas 'leon' y 'la paloma', como si existen, devuelve sus valores

None
City
Leon           Spain
La Paloma    Uruguay
Name: Country, dtype: object

In [87]:
print(city.get(780)) # Imprime los valores de la fila '780', devuelve 'none' porque no existe dicha fila

None

<ipython-input-87-bc7c82276ab4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(city.get(780))

In [89]:
city.dtype # Método 'dytpe' para acceder al tipo de datos que contiene

dtype('O')

In [90]:
city.values # Método 'values' para acceder a todos los valores de la columna 'city'

array(['Botswana', 'Spain', 'kyrgyzstan', 'Russia', 'Ireland', 'Uruguay',
       'Indonesia', 'Peru', 'Costa Rica', 'Portugal', 'Japan', 'Russia',
       'Peru', 'South Africa', 'Georgia', 'France', 'China',
       'New Zealand', 'Malaysia', 'United States', 'Philippines',
       'Philippines', 'Myanmar', 'Nicaragua', 'Morocco', 'China',
       'Uruguay', 'Russia', 'Cape Verde', 'Venezuela', 'Philippines',
       'Thailand', 'China', 'Ukraine', 'Madagascar', 'China', 'Indonesia',
       'Oman', 'Sweden', 'France', 'China', 'Gambia', 'China', 'Peru',
       'Russia', 'China', 'Russia', 'Peru', 'Dominican Republic',
       'Philippines', 'China', 'France', 'France', 'Brazil', 'Panama',
       'Ukraine', 'Indonesia', 'Philippines', 'Indonesia', 'Russia',
       'Portugal', 'Nigeria', 'Bolivia', 'China', 'Russia', 'Bulgaria',
       'China', 'Brazil', 'Russia', 'China', 'Bolivia', 'Syria',
       'Argentina', 'Ireland', 'Russia', 'Senegal', 'Indonesia',
       'Portugal', 'Thailand', 'Norway', 'Canada', 'China', 'Brazil',
       'Nigeria', 'Philippines', 'Portugal', 'Poland', 'Philippines',
       'Swaziland', 'Brazil', 'Brazil', 'Mexico', 'Indonesia', 'Thailand',
       'Philippines', 'Malawi', 'Philippines', 'Germany', 'Netherlands',
       'Mexico', 'Thailand', 'Brazil', 'Colombia', 'Philippines',
       'France', 'China', 'Indonesia', 'Indonesia', 'United States',
       'Philippines', 'Colombia', 'Thailand', 'Chile', 'Georgia',
       'Belarus', 'Canada', 'Indonesia', 'Portugal', 'Russia', 'Ukraine',
       'Lebanon', 'Portugal', 'Albania', 'Brazil', 'Indonesia',
       'Indonesia', 'Kyrgyzstan', 'New Zealand', 'Japan', 'Peru',
       'France', 'Indonesia', 'Indonesia', 'Taiwan', 'Sweden', 'Peru',
       'Czech Republic', 'Russia', 'Myanmar', 'China', 'Armenia',
       'Sweden', 'France', 'Indonesia', 'Russia', 'Ukraine', 'Thailand',
       'France', 'Croatia', 'Indonesia', 'Russia', 'Czech Republic',
       'China', 'Colombia', 'Thailand', 'Mexico', 'Japan', 'Indonesia',
       'Russia', 'Zimbabwe', 'France', 'South Korea', 'Uganda',
       'Indonesia', 'Indonesia', 'Russia', 'Eritrea', 'Thailand',
       'New Zealand', 'Indonesia', 'Mali', 'France', 'Canada', 'Nigeria',
       'Malawi', 'Ukraine', 'Indonesia', 'South Africa', 'Philippines',
       'China', 'Thailand', 'Pakistan', 'Philippines', 'Mexico',
       'Philippines', 'Estonia', 'Zimbabwe', 'China', 'Brazil',
       'Indonesia', 'Democratic Republic of the Congo', 'Netherlands',
       'Portugal', 'Morocco', 'China', 'Sweden', 'Brazil', 'Philippines',
       'Russia', 'Indonesia', 'China', 'Indonesia', 'China',
       'Philippines', 'Russia', 'Indonesia', 'Netherlands', 'Portugal',
       'Iran', 'Spain', 'Indonesia', 'Croatia', 'Madagascar', 'Peru',
       'Zambia', 'Mongolia', 'Indonesia', 'Indonesia', 'Indonesia',
       'Philippines', 'Philippines', 'Russia', 'Indonesia', 'Mexico',
       'Japan', 'Sweden', 'Brazil', 'Brazil', 'Armenia', 'South Korea',
       'Sweden', 'Mexico', 'Philippines', 'Philippines', 'Russia',
       'Portugal', 'Portugal', 'Portugal', 'Thailand', 'Mexico',
       'Finland', 'Canada', 'Indonesia', 'Finland', 'Indonesia', 'Mexico',
       'Indonesia', 'Colombia', 'Portugal', 'Uganda', 'Comoros',
       'Indonesia', 'Comoros', 'Peru', 'Philippines', 'Nepal', 'Brazil',
       'Paraguay', 'China', 'Estonia', 'Indonesia', 'China', 'Indonesia',
       'Dominican Republic', 'Portugal', 'Chile', 'Mexico', 'France',
       'Indonesia', 'Peru', 'China', 'France', 'Guatemala',
       'Czech Republic', 'Portugal', 'Malaysia', 'Ukraine', 'China',
       'France', 'Indonesia', 'Argentina', 'Malaysia', 'Indonesia',
       'Indonesia', 'China', 'China', 'China', 'Indonesia', 'Russia',
       'Venezuela', 'Nigeria', 'Indonesia', 'Peru', 'Pakistan', 'Mexico',
       'France', 'Poland', 'Maldives',
       'Bonaire, Saint Eustatius and Saba ', 'Indonesia', 'Indonesia',
       'Thailand', 'United States', 'Russia', 'Panama', 'Indonesia',
       'Afghanistan', 'Indonesia', 'Ecuador', 'Chile', 'Philippines',
       'Indonesia', 'Sweden', 'China', 'Canada', 'Indonesia', 'Kenya',
       'Philippines', 'Indonesia', 'Ukraine', 'Dominican Republic',
       'Indonesia', 'Indonesia', 'South Korea', 'Canada', 'United States',
       'United States', 'Micronesia', 'Yemen', 'Colombia', 'Russia',
       'Netherlands', 'Sierra Leone', 'Indonesia', 'Philippines',
       'Philippines', 'Philippines', 'Indonesia', 'Russia', 'Philippines',
       'Indonesia', 'Indonesia', 'Indonesia', 'Colombia',
       'Czech Republic', 'China', 'Norway', 'Bulgaria', 'China',
       'Indonesia', 'Madagascar', 'Pakistan', 'Indonesia',
       'Dominican Republic', 'Indonesia', 'Sweden', 'China', 'Russia',
       'Argentina', 'Russia', 'China', 'Brazil', 'Czech Republic',
       'China', 'Ecuador', 'Nigeria', 'Myanmar', 'Russia', 'China',
       'China', 'Sri Lanka', 'Armenia', 'Portugal', 'Indonesia', 'China',
       'New Zealand', 'Indonesia', 'United States', 'Portugal', 'China',
       'Indonesia', 'Myanmar', 'Czech Republic', 'Honduras',
       'Bosnia and Herzegovina', 'Thailand', 'China', 'Portugal',
       'Indonesia', 'Indonesia', 'Botswana', 'United States', 'France',
       'Indonesia', 'Poland', 'Colombia', 'Panama', 'Russia', 'Russia',
       'Indonesia', 'Portugal', 'Brazil', 'Russia', 'China', 'Brazil',
       'Ukraine', 'Sweden', 'Indonesia', 'United Arab Emirates',
       'Indonesia', 'Canada', 'Cape Verde', 'Nigeria', 'Czech Republic',
       'China', 'China', 'China', 'South Africa', 'Ukraine', 'Russia',
       'Philippines', 'Russia', 'Colombia', 'Nigeria', 'Chile',
       'Portugal', 'Brazil', 'China', 'Netherlands',
       'Palestinian Territory', 'Tajikistan', 'Netherlands', 'Guatemala',
       'Belarus', 'Pakistan', 'Armenia', 'China', 'China', 'China',
       'Botswana', 'China', 'United States', 'Indonesia', 'Russia',
       'France', 'South Korea', 'Indonesia', 'United States', 'France',
       'Guinea', 'Indonesia', 'Ukraine', 'Philippines', 'United States',
       'Canada', 'China', 'Tajikistan', 'Spain', 'Finland', 'Macedonia',
       'Chad', 'Thailand', 'China', 'China', 'Denmark', 'Poland',
       'Indonesia', 'Portugal', 'Peru', 'Philippines', 'Japan',
       'Indonesia', 'Democratic Republic of the Congo', 'Brazil', 'Kenya',
       'Canada', 'Peru', 'Slovenia', 'Thailand', 'Peru', 'Poland',
       'Poland', 'Portugal', 'Indonesia', 'China', 'Philippines', 'Japan',
       'Mongolia', 'France', 'Russia', 'Indonesia', 'Zambia',
       'Palestinian Territory', 'Argentina', 'China', 'Yemen', 'Russia',
       'Indonesia', 'Philippines', 'Brazil', 'Poland', 'China',
       'Philippines', 'Canada', 'Indonesia', 'Indonesia', 'Bulgaria',
       'Philippines', 'Portugal', 'Thailand', 'Egypt', 'Ethiopia',
       'Russia', 'Indonesia', 'Serbia', 'Papua New Guinea', 'Mauritius',
       'South Africa', 'United Kingdom', 'Philippines', 'Poland',
       'Philippines', 'Philippines', 'Indonesia', 'Philippines',
       'Portugal', 'China', 'China', 'Indonesia', 'Indonesia',
       'Philippines', 'Indonesia', 'China', 'South Korea', 'Canada',
       'Portugal', 'Philippines', 'China', 'China', 'Indonesia',
       'Belarus', 'Armenia', 'China', 'France', 'Slovenia', 'Ireland',
       'Russia', 'South Korea', 'France', 'Sudan', 'Russia', 'Mexico',
       'Afghanistan', 'Japan', 'Malaysia', 'United States', 'Portugal',
       'Japan', 'Sweden', 'Philippines', 'United States', 'Peru', 'China',
       'Philippines', 'China', 'Brazil', 'Brazil', 'Russia',
       'Philippines', 'Indonesia', 'Thailand', 'United States', 'Peru',
       'France', 'Tanzania', 'Chile', 'Canada', 'Vietnam', 'Egypt',
       'Philippines', 'Russia', 'Nigeria', 'Indonesia', 'China', 'China',
       'Thailand', 'Japan', 'China', 'Philippines', 'Philippines',
       'Indonesia', 'Philippines', 'China', 'Japan', 'Peru', 'Albania',
       'Peru', 'Germany', 'Zimbabwe', 'Nigeria', 'Canada'], dtype=object)

In [91]:
population = pop
population

     Population
0         21722
1          5629
2          5679
3         10085
4         23421
..          ...
596       10024
597        5768
598       16679
599       24800
600       13000

[601 rows x 1 columns]

In [92]:
population = pop["Population"]
population

0      21722
1       5629
2       5679
3      10085
4      23421
       ...
596    10024
597     5768
598    16679
599    24800
600    13000
Name: Population, Length: 601, dtype: int64

In [93]:
population.dtype # Método ya explicado

dtype('int64')

In [94]:
#pop.values
population.values # Método 'values' para acceder a todos los valores de 'population'

array([21722,  5629,  5679, 10085, 23421, 22154, 11558, 13288,  5835,
        9942, 18354,  8184,  4672, 10733, 16577, 13265, 38745, 10120,
       16567, 24397, 15170,  5589, 17693,  2545, 21997, 11174, 21758,
        5860, 13204, 24943,  7476, 18560, 16422, 20559,  8519, 24805,
       20119,  5283, 19947, 16254,  9746,  4187,  3515, 22829,  4431,
       11071,  5972, 23638,  5217, 19156, 24196,  3106,  5428, 20167,
       15519, 24424, 20539, 13138, 11393, 22345, 19021, 22267, 23801,
       19485,  2653,  8634, 10173,  2528,  7332, 18425, 16527,  3103,
       22667,  6901,  5532, 24272, 20178, 14050, 22908, 22016, 10667,
       12517, 21987,  3900, 16041,  3507,  4002, 13997, 21675, 13299,
       11913, 24383, 14784, 14841,  2863, 16916, 13234,  5349, 22436,
       12620, 10021, 20120, 20168, 21621,  3695, 24722, 18096, 15913,
       19734, 17535, 13034,  4291, 18899, 21153, 12967, 17231, 23458,
       15394, 17005,  4779,  9960, 14226, 13161, 13443,  6955,  8307,
        7193, 13518, 14385, 10188,  5470, 17720, 21409, 11147, 13966,
       13041, 21697,  3200,  3005, 12141, 18956,  2972, 19063,  4962,
       12426, 14596, 11859, 18173,  5611,  3571, 15853,  6255, 13471,
       19698, 11250, 19580, 23588, 24437,  3241,  7960, 23179,  9431,
       12626, 24666, 21762,  3587,  4718, 20044, 23203,  6128, 15691,
        4930,  9031, 20048, 14258, 18716,  4181,  8103,  2568, 11008,
       16102,  3590, 12138,  7305, 24995, 15642, 22334, 21408,  3517,
        6013, 22762,  8531, 15223, 19066, 13500, 11236, 15189, 15509,
        6348, 13232, 13272, 14500, 21095, 12316, 12321,  7891, 20061,
        8776,  5482, 17317,  7830, 18615, 17492,  7641, 11549, 17235,
       18605,  4143, 10196, 24325, 20967, 17620,  4157, 18941, 13596,
       13161,  3867,  3912,  2581, 19090,  7251, 18192, 12353, 20756,
       20208,  8650, 14298, 24248, 17394, 22346,  6419, 17373, 23184,
       15229, 12186,  2533, 24789,  7337, 20537, 18399, 12021, 24391,
       22589, 13603,  5386, 22900, 16650,  8247, 12718,  6348, 24060,
       16111,  3467, 18244, 23793, 22181, 22168, 11901, 15224, 16306,
       21340, 20551, 17272,  7331,  2752, 24020, 11693,  3295,  2936,
       15775, 13827, 10896,  9929, 20654, 15348,  4681,  3045, 23061,
       18726, 20079, 21465,  9850, 23005, 14668,  5661,  7446, 15090,
       10277,  9122, 23690, 12433, 18118,  4352, 21721, 22601,  8055,
       19890,  7252,  3826, 21146, 11618,  4517, 10444, 21774, 12835,
        3162, 12282, 24771,  3960, 23053, 16040,  4231,  2574, 20111,
       22001, 21790,  7689,  9936, 17818, 16783, 22054, 20220, 21183,
       15897,  4534, 21600, 24095,  4539, 12736,  5851,  3020, 16395,
       23665, 22968, 12765, 22175,  6504,  7969, 24670, 16996, 18126,
       12242, 12348,  3885,  5415, 12126, 20512, 15738, 21540,  2862,
       12397, 24614, 19686, 13014, 10688, 12411, 16375, 18678, 16148,
       13872, 16996,  4654, 23396, 19101,  4978,  3622, 17663, 18705,
        5763, 23452, 15496, 18741,  8022, 18205, 20144,  5247,  3416,
       10496,  9367, 24722, 15864, 11267,  3610, 20361, 18007, 14073,
       24475,  6833, 21271, 21938,  4065, 19752, 23290, 20067, 16208,
       21270, 16389,  9808, 13423, 22811, 18435,  9430,  5247, 13627,
       18243,  7127, 22095,  3370, 17647, 18066,  2797, 12076,  3596,
       21216,  2772, 17560, 11364, 13086, 22781,  4984, 15368, 11291,
       13344, 21760, 24385, 22361, 23914,  8612, 10223, 15487, 22073,
        9632,  4812, 12541, 24958,  2809,  6699, 14768, 16258, 11630,
       24800, 14918, 11090,  7801, 11761,  4201,  6376,  6507, 19797,
       14989, 13989,  8550, 13430, 21824, 16421, 12001, 24186, 22000,
       11553, 11688, 18159, 11645, 21555,  6655, 15734, 18856,  4617,
        8882, 12530, 14436,  7791,  3163,  3946, 10175, 24808,  5379,
        6520,  7049, 22750, 11695, 13252,  3284, 18819, 11151, 19895,
       11064,  9725,  5230,  6165,  4455, 16381, 19337, 20739,  5841,
        6281, 15649,  3126, 13875,  3358,  4949, 12666, 10440, 14053,
       24989,  9593, 16078, 16386,  7322, 13885,  7347, 24753, 17549,
       19366, 17631,  6961,  8209, 23796,  7299, 23804,  6942, 13500,
       16973, 16832, 19525, 24090, 24669, 15031, 21275,  6105, 19443,
       14669, 18373, 20383, 23981,  3135, 13448, 12112,  5356,  5964,
       15892,  5273, 15770, 15923,  9106, 13275, 16795, 22569, 14495,
       22342, 13766,  7307, 21426, 10701, 16307, 10710, 12357, 19005,
       22671,  7514, 13979,  4602,  6759, 19212, 10634,  6658,  5048,
       19561, 21988, 21421,  8361, 10012, 17400, 21444, 24751, 18087,
        6055, 18843, 21704, 11094,  3803, 23737, 11949,  4114, 16755,
       16325, 16905, 10024,  5768, 16679, 24800, 13000])

In [ ]:
city.index # Método 'index' devuelve el índice de 'city'

Index(['Abuja', 'Aizhai', 'Aketi', 'Alarobia', 'Alcoutim', 'Alis',
       'Alvaro Obregon', 'Amargosa', 'Amuru', 'Anan',
       ...
       'Zhangcun', 'Zhangzhu', 'Zhatay', 'Zhentou', 'Zhiletovo',
       'Zhongshangang', 'Zhongshangang', 'Zhongxing', 'Zhuoshui', 'Zliv'],
      dtype='object', name='City', length=601)

In [95]:
population.index # Método 'index' devuelve el índice de 'population'

RangeIndex(start=0, stop=601, step=1)

In [96]:
city.is_unique # Método 'is_unique' devuelve un valor booleano si los valores de 'city' son únicos

False

In [97]:
population.is_unique # Método 'is_unique' devuelve un valor booleano si los valores de 'population' son únicos

False

In [98]:
city.ndim # Método 'ndim' devuelve el número/cantidad de dimenisones de la estructura de datos

1

In [99]:
#pop.ndim
population.ndim # Método 'ndim' devuelve el número/cantidad de dimenisones de la estructura de datos

1