Gustavo A. Aparicio V. - 20232005091

In [ ]:
import pandas as pd

In [ ]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]} # Crea un diccionario

In [ ]:
pd.DataFrame(data) # Al dataframe 'pd' se le añade el diccionario 'data'

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

In [ ]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"]) # Cambia los valores del índice

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male